Drivers
WildCodeSchool/lille-0920-js-p3-toidemain pull request #14
Opened 2021-01-11 10:09 UTC by gaetan-cordonnier

Component Drivers with modal is functional.

2021-01-11 10:28 UTC, Guy-deMessimy submitted a review, later dismissed

2021-01-11 14:38 UTC, gaetan-cordonnier reviewed
Conflicts resolved.

2021-01-11 14:53 UTC, Guy-deMessimy submitted a review, later dismissed

2021-01-11 17:53 UTC, AmjadLille submitted a review, later dismissed

2021-01-12 09:58 UTC, Guy-deMessimy submitted a review, later dismissed

2021-01-12 13:41 UTC, LoicBrassart requested changes
Please refactor this code

2021-01-12 13:41 UTC, LoicBrassart commented on public/images/animated_background.svg
> +            @keyframes float1 {
Wait, what ? No !
CSS goes in a separate file !

2021-01-12 13:41 UTC, LoicBrassart commented on src/components/Drivers/Modal/Data.jsx
> +const driverItems = [
This object is futilely complex, you could simplify it a lot!
- Don't open a global object in the array
- Don't add artificial IDs as keys
=> You have an array, with every element being an Object, even IDs can be kept in them if needed

2021-01-12 13:41 UTC, LoicBrassart commented on src/components/Drivers/Modal/index.jsx
> +  console.log(itemNumber);
No `console.log`

2021-01-12 13:41 UTC, LoicBrassart commented on src/components/Drivers/index.jsx
> +  console.log(isOpen);
Neither here

2021-01-12 13:41 UTC, LoicBrassart commented on src/components/Drivers/index.jsx
> +  let [driverItem, setDriverItem] = useState();
Why use `let` ?

2021-01-12 13:41 UTC, LoicBrassart commented on src/components/Drivers/index.jsx
> +              setIsOpen(true, setDriverItem((driverItem = 1)))
`driverItem = 1` ? That probably does not do what you think it does

2021-01-12 13:49 UTC, gaetan-cordonnier commented on src/components/Drivers/index.jsx
> +              setIsOpen(true, setDriverItem((driverItem = 1)))
"driverItem = 1" -> It's correct this is the number of Hexagon Index

2021-01-18 15:55 UTC, gaetan-cordonnier commented on public/images/animated_background.svg
> +            @keyframes float1 {
Resolved

2021-01-18 15:55 UTC, gaetan-cordonnier commented on src/components/Drivers/Modal/index.jsx
> +  console.log(itemNumber);
Resolved

2021-01-18 15:56 UTC, gaetan-cordonnier commented on src/components/Drivers/index.jsx
> +  console.log(isOpen);
It's correct, it's for the library

2021-01-18 15:56 UTC, gaetan-cordonnier commented on src/components/Drivers/index.jsx
> +  let [driverItem, setDriverItem] = useState();
Resolved

2021-01-18 15:56 UTC, gaetan-cordonnier commented on src/components/Drivers/index.jsx
> +              setIsOpen(true, setDriverItem((driverItem = 1)))
Resolved

2021-01-19 10:11 UTC, gaetan-cordonnier commented on public/images/animated_background.svg
> +            @keyframes float1 {
Image deleted on folder

2021-01-19 10:14 UTC, AmjadLille submitted a review, later dismissed

2021-01-19 10:18 UTC, AmjadLille approved these changes, later dismissed

2021-01-19 15:45 UTC, LoicBrassart commented on src/components/Drivers/index.jsx
> +  console.log(isOpen);
Nope, no `console.log` is correct

2021-01-20 13:46 UTC, AmjadLille submitted a review, later dismissed

2021-01-21 08:53 UTC, AmjadLille submitted a review, later dismissed

2021-01-21 09:32 UTC, Guy-deMessimy submitted a review, later dismissed

2021-01-21 09:48 UTC, LoicBrassart submitted a review, later dismissed
SnE

2021-01-21 09:58 UTC, Guy-deMessimy submitted a review, later dismissed

2021-01-21 10:04 UTC, AmjadLille approved these changes

2021-01-21 10:10 UTC, Guy-deMessimy approved these changes

2021-01-21 17:16 UTC, LoicBrassart approved these changes
SnE

2021-01-21 17:23 UTC, merged