HomeButton
WildCodeSchool/lille-0920-js-p3-toidemain pull request #26
Opened 2021-01-18 14:48 UTC by Guy-deMessimy

2021-01-18 21:23 UTC, AmjadLille submitted a review, later dismissed

2021-01-19 15:30 UTC, LoicBrassart requested changes
Once again, a wild `console.log` appears

2021-01-19 15:30 UTC, LoicBrassart commented on src/components/HomeButton/index.jsx
> +  }
Nope

2021-01-20 12:58 UTC, AmjadLille approved these changes

2021-01-21 09:31 UTC, LoicBrassart approved these changes
SnE

2021-01-21 09:32 UTC, merged