ButtonText
WildCodeSchool/lille-0920-js-p3-toidemain pull request #27
Opened 2021-01-19 09:31 UTC by Guy-deMessimy

2021-01-19 10:43 UTC, AmjadLille submitted a review, later dismissed

2021-01-19 15:28 UTC, AmjadLille approved these changes, later dismissed

2021-01-19 15:34 UTC, LoicBrassart requested changes
*One* Minor Evil

2021-01-19 15:34 UTC, LoicBrassart commented on src/pages/home/index.jsx
> +
Useless, and a Prettier missing proof

2021-01-19 15:48 UTC, AmjadLille approved these changes

2021-01-21 09:36 UTC, LoicBrassart approved these changes
SnE

2021-01-21 09:45 UTC, merged