Stage up
WildCodeSchool/lille-0920-js-p3-toidemain pull request #31
Opened 2021-01-19 10:28 UTC by AmjadLille

2021-01-19 14:04 UTC, Guy-deMessimy submitted a review, later dismissed

2021-01-19 15:20 UTC, Guy-deMessimy approved these changes, later dismissed

2021-01-19 15:38 UTC, Guy-deMessimy approved these changes, later dismissed

2021-01-19 16:11 UTC, LoicBrassart requested changes
Prettify

2021-01-19 16:11 UTC, LoicBrassart commented on src/components/Header/Navbar/index.jsx
> +          <a href="#!">Nos Actions</a>
What's that ?

2021-01-19 16:11 UTC, LoicBrassart commented on src/components/Header/Navbar/index.jsx
> +            <Link to="/about/#equipe">Notre Equipe</Link>
Useless `#` ?

2021-01-19 16:11 UTC, LoicBrassart commented on src/App.js
> +import { AppStyle } from './style.jsx';
Prettify

2021-01-19 16:11 UTC, LoicBrassart commented on src/components/Title/style.js
> +import styled from 'styled-components';
Prettify

2021-01-19 16:11 UTC, LoicBrassart commented on src/components/Title/style.js
> +  font-family: 'Roboto', sans-serif;
Prettify

2021-01-19 16:11 UTC, LoicBrassart commented on src/style.jsx
> +import styled from 'styled-components';
Prettify

2021-01-19 16:11 UTC, LoicBrassart commented on src/style.jsx
> +  font-family: 'Roboto', sans-serif;
Prettify

2021-01-20 09:21 UTC, Guy-deMessimy approved these changes

2021-01-21 09:34 UTC, closed without merging