Soutenir
WildCodeSchool/lille-0920-js-p3-toidemain pull request #40
Opened 2021-01-22 18:50 UTC by AmelMac

2021-01-23 11:50 UTC, AmjadLille requested changes

2021-01-23 11:50 UTC, AmjadLille commented on src/components/Header/Navbar/index.jsx
> +        |<a href="/soutenir">Nous Soutenir</a>|
replace <a> by <Link>

2021-01-23 14:43 UTC, AmelMac commented on src/components/Header/Navbar/index.jsx
> +        |<a href="/soutenir">Nous Soutenir</a>|
ok! :)

2021-01-24 13:56 UTC, AmjadLille submitted a review, later dismissed

2021-01-25 08:14 UTC, LoicBrassart requested changes
You forgot to use Prettier... Too bad, no Evils beyond that

2021-01-25 08:14 UTC, LoicBrassart commented on src/pages/soutenir/index.jsx
> +    <>
Tip: If your component has a single parent container (here, the aptly named `<SoutenirContainer>`), you don't need the `<>` tag ;-)

2021-01-25 08:14 UTC, LoicBrassart commented on src/pages/soutenir/style.js
> +padding: 1vh;
You forgot my Prettify ;_;

2021-01-25 09:07 UTC, AmjadLille submitted a review, later dismissed

2021-01-27 08:30 UTC, LoicBrassart requested changes
I think you broke something

2021-01-27 08:30 UTC, LoicBrassart commented on src/components/Header/Navbar/index.jsx
> +        <Link href="/actualite">Notre Actualité</Link>|
Wait, why did you change that ?

2021-01-27 08:30 UTC, LoicBrassart commented on src/pages/soutenir/style.js
> +padding: 1vh;
Still no Prettify ?

2021-01-27 08:59 UTC, AmjadLille approved these changes, later dismissed

2021-01-27 09:03 UTC, AmjadLille approved these changes

2021-01-27 09:21 UTC, LoicBrassart approved these changes
SnE

2021-01-27 09:21 UTC, merged