configure emailjs and set state for template email
WildCodeSchool/lille-0920-js-p3-toidemain pull request #44
Opened 2021-01-27 15:54 UTC by Guy-deMessimy

2021-01-28 09:38 UTC, AmjadLille submitted a review, later dismissed

2021-01-30 09:08 UTC, LoicBrassart submitted a review, later dismissed
SnE

2021-01-30 10:43 UTC, AmjadLille approved these changes

2021-02-01 08:16 UTC, LoicBrassart requested changes
I think you made a mistake, please check it

2021-02-01 08:16 UTC, LoicBrassart commented on package.json
> +  }
You make me doubt myself...
This change seems to me it will break everything (add only one bracket, without it's counterpart)

2021-02-01 08:25 UTC, LoicBrassart approved these changes
Nevermind, my mistake!

2021-02-01 08:26 UTC, merged