Login page
WildCodeSchool/lille-0920-js-p3-toidemain pull request #45
Opened 2021-01-28 21:21 UTC by gaetan-cordonnier

2021-01-29 09:33 UTC, AmjadLille submitted a review, later dismissed

2021-01-30 09:21 UTC, LoicBrassart submitted a review, later dismissed
SnE

2021-01-30 10:48 UTC, AmjadLille approved these changes

2021-02-01 08:17 UTC, LoicBrassart requested changes
I want to see if these PR break `dev`

2021-02-01 08:17 UTC, LoicBrassart commented on package.json
> +  }
... Still doubting

2021-02-01 08:25 UTC, LoicBrassart approved these changes
Nope, that's me, sorry!

2021-02-01 08:26 UTC, merged